Vagrant.configure("2") do |config|

  config.vm.define "edelageS" do |server|
    server.vm.box = "debian/bookworm64"

    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.hostname = "edelageS"

    server.vm.synced_folder "./data", "/vagrant"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1

      vb.name = "edelageS"
    end


    server.vm.provision "shell", inline: <<-SHELL
      sudo systemctl stop nftables
      sudo systemctl disable nftables
      apt-get update
      apt-get install -y curl
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface=eth1" sh -
      cp /var/lib/rancher/k3s/server/node-token /vagrant
      kubectl apply -f /vagrant/config/app1.yaml
      kubectl apply -f /vagrant/config/app2.yaml
      kubectl apply -f /vagrant/config/app3.yaml
      kubectl apply -f /vagrant/config/ingress.yaml
    SHELL
  end
end
