Vagrant.configure("2") do |config|

  config.vm.define "edelageS" do |server|
    server.vm.box = "debian/bookworm64"

    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.hostname = "edelageS"

    server.vm.synced_folder "./data", "/vagrant"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1

      vb.name = "edelageS"
    end


    server.vm.provision "shell", inline: <<-SHELL
      sudo systemctl stop nftables
      sudo systemctl disable nftables
      apt-get update
      apt-get install -y curl
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface=eth1" sh -
      cp /var/lib/rancher/k3s/server/node-token /vagrant
    SHELL
  end

  config.vm.define "edelageSW" do |worker|
    worker.vm.box = "debian/bookworm64"

    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.hostname = "edelageSW"

    worker.vm.synced_folder "./data", "/vagrant"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1

      vb.name = "edelageSW"
    end


    worker.vm.provision "shell", inline: <<-SHELL
      sudo systemctl stop nftables
      sudo systemctl disable nftables
      apt-get update
      apt-get install -y curl
      curl -sfL https://get.k3s.io | K3S_URL=https://'192.168.56.110:6443' K3S_TOKEN_FILE='/vagrant/node-token' INSTALL_K3S_EXEC='--flannel-iface=eth1' sh -
    SHELL
  end
end
